section .data
colon "very_long", very_long_word
db "qwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwertyqwerty",0

colon "test", test_word
db "test word of dictionary",0

colon "empty", empty_word
db 0

colon "russian", russian_word
db "Русский текст", 0

colon "normal", nomal_word
db "Typicall word that are expected to be stored in dictionary", 0

colon "first", first_word
db "first word of dictionary",0